# netlify.toml

# Regla para interceptar todo el tr치fico y mostrar la p치gina de mantenimiento.
# Esto es una REESCRITURA (rewrite), no una redirecci칩n.
# La URL en el navegador del usuario no cambiar치.

[[redirects]]
  from = "/*"
  to = "/maintenance.html"
  status = 200